---
#- hosts: ios
#  gather_facts: no
#  tasks:
#  - ios_command:
#      commands:
#        - show arp

- hosts: nxos
  gather_facts: no
  connection: local
  tasks:
  - nxos_command:
      commands:
        - "show ip arp | json"
      provider: "{{ cli }}"
    register: printout
  - debug: var=vars
  - set_fact:
      output: "{{ printout.result|from_json }}"
